### ISSUE TITLE
Template error in Craft 3.4

### ISSUE THREAD

**Issue by dwhoban** [olivierbon/craft-concierge#13]
I know its still in Beta but the following error is thrown as the `_elements/indexcontainer` file has been remove by Craft

```
craft\web\twig\TemplateLoaderException: Unable to find the template “_elements/indexcontainer” in "concierge" at line 23. in /var/www/vendor/craftcms/cms/src/web/twig/TemplateLoader.php:125
Stack trace:
#0 /var/www/vendor/craftcms/cms/src/web/twig/TemplateLoader.php(78): craft\web\twig\TemplateLoader->_resolveTemplate('_elements/index...')
#1 /var/www/vendor/twig/twig/src/Environment.php(299): craft\web\twig\TemplateLoader->getCacheKey('_elements/index...')
#2 /var/www/vendor/twig/twig/src/Environment.php(381): Twig\Environment->getTemplateClass('_elements/index...')
#3 /var/www/vendor/craftcms/cms/src/web/twig/Environment.php(44): Twig\Environment->loadTemplate('_elements/index...', NULL)
#4 /var/www/vendor/twig/twig/src/Template.php(335): craft\web\twig\Environment->loadTemplate('_elements/index...', NULL)
#5 /var/www/storage/runtime/compiled_templates/fd/fd7c7774c7f4755639c8585993892cd53f4605b359e9e9b31facfc0fde9077b5.php(116): Twig\Template->loadTemplate('_elements/index...', 'concierge', 23)
#6 /var/www/vendor/twig/twig/src/Template.php(184): __TwigTemplate_3689907fb8aa40ac9283fe53fcdd998b1e4809a7de149130efaedb5609512388->block_content(Array, Array)
#7 /var/www/storage/runtime/compiled_templates/cc/cccadb1db004bc9a92ee27b3823047047c59c54efa530e96b37f73670058f291.php(408): Twig\Template->displayBlock('content', Array, Array)
#8 /var/www/vendor/twig/twig/src/Template.php(184): __TwigTemplate_53d66f293e4d511a318a3218f1082a8f0ecf3c5159067d0d69aac4d341d7fbcb->block_main(Array, Array)
#9 /var/www/storage/runtime/compiled_templates/cc/cccadb1db004bc9a92ee27b3823047047c59c54efa530e96b37f73670058f291.php(263): Twig\Template->displayBlock('main', Array, Array)
#10 /var/www/vendor/twig/twig/src/Template.php(184): __TwigTemplate_53d66f293e4d511a318a3218f1082a8f0ecf3c5159067d0d69aac4d341d7fbcb->block_body(Array, Array)
#11 /var/www/storage/runtime/compiled_templates/74/7443b984c04032d0fbccc4f0731aeffe8fb212b9af29f791ad284a3868c55831.php(75): Twig\Template->displayBlock('body', Array, Array)
#12 /var/www/vendor/twig/twig/src/Template.php(407): __TwigTemplate_c4d990dc702cef244edf95c30320acc766de4cd6bbce9623b6b62e7a2e131c28->doDisplay(Array, Array)
#13 /var/www/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#14 /var/www/storage/runtime/compiled_templates/79/7921ddcc17503cda8bb1cc52f143267a729c390edec6c49171c8e95d15c657ad.php(56): Twig\Template->display(Array, Array)
#15 /var/www/vendor/twig/twig/src/Template.php(407): __TwigTemplate_a9ac15f4be42966ebf5778aca26a40eed58aaace48321e27bc08fc0a7f71758b->doDisplay(Array, Array)
#16 /var/www/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#17 /var/www/storage/runtime/compiled_templates/cc/cccadb1db004bc9a92ee27b3823047047c59c54efa530e96b37f73670058f291.php(137): Twig\Template->display(Array, Array)
#18 /var/www/vendor/twig/twig/src/Template.php(407): __TwigTemplate_53d66f293e4d511a318a3218f1082a8f0ecf3c5159067d0d69aac4d341d7fbcb->doDisplay(Array, Array)
#19 /var/www/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#20 /var/www/storage/runtime/compiled_templates/fd/fd7c7774c7f4755639c8585993892cd53f4605b359e9e9b31facfc0fde9077b5.php(62): Twig\Template->display(Array, Array)
#21 /var/www/vendor/twig/twig/src/Template.php(407): __TwigTemplate_3689907fb8aa40ac9283fe53fcdd998b1e4809a7de149130efaedb5609512388->doDisplay(Array, Array)
#22 /var/www/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#23 /var/www/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#24 /var/www/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#25 /var/www/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#26 /var/www/vendor/craftcms/cms/src/web/View.php(399): Twig\Environment->render('concierge', Array)
#27 /var/www/vendor/craftcms/cms/src/web/View.php(460): craft\web\View->renderTemplate('concierge', Array)
#28 /var/www/vendor/craftcms/cms/src/web/Controller.php(244): craft\web\View->renderPageTemplate('concierge', Array, 'cp')
#29 /var/www/vendor/craftcms/cms/src/controllers/TemplatesController.php(104): craft\web\Controller->renderTemplate('concierge', Array)
#30 [internal function]: craft\controllers\TemplatesController->actionRender('concierge', Array)
#31 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#32 /var/www/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#33 /var/www/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('render', Array)
#34 /var/www/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#35 /var/www/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('templates/rende...', Array)
#36 /var/www/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#37 /var/www/vendor/craftcms/cms/src/web/Application.php(284): yii\web\Application->handleRequest(Object(craft\web\Request))
#38 /var/www/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#39 /var/www/web/index.php(21): yii\base\Application->run()
#40 {main}
```

**Comment by olivierbon** [comment]
Craft [added a fix](https://github.com/craftcms/cms/commit/043a24f339e319f489cee15c8b6025772587e5c9) for this which should be out next release and I will do some work on my side too to improve things.
